# Generated by Django 5.1.1 on 2024-10-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
